FROM eclipse-temurin:21-jdk AS build
WORKDIR /app
COPY gradlew settings.gradle build.gradle ./
COPY gradle ./gradle
COPY common ./common
COPY ticketing-core ./ticketing-core
RUN mkdir -p queue-gate admission-worker
RUN chmod +x gradlew && ./gradlew :ticketing-core:bootJar --no-daemon

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/ticketing-core/build/libs/*.jar app.jar
EXPOSE 8030
ENTRYPOINT ["java", "-jar", "app.jar"]
